// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phonebook;

#nullable disable

namespace Phonebook.Migrations
{
    [DbContext(typeof(PhonebookContext))]
    [Migration("20260610093320_SeedInitialContacts")]
    partial class SeedInitialContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Phonebook.Model.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "johnDoe@gmail.com",
                            Name = "John Doe",
                            PhoneNumber = "110000111"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "john.doe@gmail.com",
                            Name = "John Doe",
                            PhoneNumber = "114345111"
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "maryjane@gmail.com",
                            Name = "Mary Jane",
                            PhoneNumber = "110500631"
                        },
                        new
                        {
                            Id = 4,
                            EmailAddress = "alicegreen@gmail.com",
                            Name = "Alice Green",
                            PhoneNumber = "120305141"
                        },
                        new
                        {
                            Id = 5,
                            EmailAddress = "bobvance@gmail.com",
                            Name = "Bob Vance",
                            PhoneNumber = "120775991"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
